spring.application.name=InformationSystemsLab1

spring.datasource.url=jdbc:postgresql://localhost:5432/InformationSystemsLab1
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.database-platform=org.eclipse.persistence.platform.database.PostgreSQLPlatform

spring.jpa.show-sql=true